name: Main

on:
  push:
    branches:
      - master
      - next
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20, 22, 24]
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: ${{ matrix.node-version }}
      - name: Prepare
        run: npm ci
      - name: Check sources
        run: npm run check
      - name: Test
        run: npm run test -- --coverage
      - name: Coveralls
        if: matrix.node-version == 22
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        run: npm run build
